/* eslint-disable */
/**
 * Generated by Convex. Regenerated automatically by `npx convex dev`.
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * @module
 */

import type * as players from "../players.js";
import type * as progress from "../progress.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  players: typeof players;
  progress: typeof progress;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
