/* eslint-disable */
/**
 * Generated by Convex. Regenerated automatically by `npx convex dev`.
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
